version: '2'
services:
  router:
    container_name: isaac-router
    image: nginx:1.9.11
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl.conf:/etc/nginx/ssl.conf
      - /local/data/dhparam.pem:/dhparam.pem
      - /local/data/certificates:/letsencrypt
      - ./html:/usr/share/nginx/html
    restart: always
  letsencrypt:
    container_name: letsencrypt
    build:
      context: .
      dockerfile: Dockerfile-letsencrypt
    image: isaac-letsencrypt
    volumes:
      - /local/data/certificates:/etc/letsencrypt
      - ./html:/var/www
networks:
  default:
    external:
      name: isaac
