services:
  router:
    container_name: isaac-router
    image: nginx:1.30
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /local/data/dhparam.pem:/dhparam.pem:ro
      - /local/data/certificates:/letsencrypt:ro
      - /local/data/cdn:/var/cdn:ro
      - ./html:/usr/share/nginx/html:ro
      - ./conf:/etc/nginx/conf:ro
    networks:
      - isaac
    restart: always

  loadbalancer:
    image: haproxy:3.4
    container_name: isaac-loadbalancer
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /local/data/haproxy/credentials.cfg:/usr/local/etc/haproxy/credentials.cfg:ro
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    environment:
      - REMOTE_SERVER_IP=$REMOTE_SERVER_IP
    networks:
      - isaac
      - isaacipv6
    command: haproxy -f /usr/local/etc/haproxy/
    restart: always

networks:
  default:
  isaac:
    name: isaac
    external: true
  isaacipv6:
    name: isaacipv6
    external: true
