version: '2'
services:
  router:
    container_name: isaac-router
    image: nginx:1.13.8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl.conf:/etc/nginx/ssl.conf
      - ./set-headers.conf:/etc/nginx/set-headers.conf
      - ./proxy-set-headers.conf:/etc/nginx/proxy-set-headers.conf
      - ./websocket-headers.conf:/etc/nginx/websocket-headers.conf
      - /local/data/dhparam.pem:/dhparam.pem
      - /local/data/certificates:/letsencrypt
      - /local/data/cdn:/var/cdn:ro
      - ./html:/usr/share/nginx/html
    restart: always
    external_links:
      - "isaac-tickets:isaac-tickets"
      - "isaac-editor:isaac-editor"
  letsencrypt:
    container_name: letsencrypt
    build:
      context: .
      dockerfile: Dockerfile-letsencrypt
    image: isaac-letsencrypt
    volumes:
      - /local/data/certificates:/etc/letsencrypt
      - ./html:/var/www
networks:
  default:
    external:
      name: isaac
