version: '2'
services:
  router:
    container_name: isaac-router
    image: nginx:1.26
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /local/data/dhparam.pem:/dhparam.pem
      - /local/data/certificates:/letsencrypt
      - /local/data/cdn:/var/cdn:ro
      - ./html:/usr/share/nginx/html
      - ./conf:/etc/nginx/conf:ro
    restart: always
networks:
  default:
    external:
      name: isaac
