version: '2'
services:
  router:
    container_name: isaac-router
    image: nginx:1.9.11
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl.conf:/etc/nginx/ssl.conf
      - /local/data/certificates:/isaac-certs
      - ./html:/usr/share/nginx/html
    restart: always
networks:
  default:
    external:
      name: isaac
